MWE of `auto_parallel_strategy` API
pytorch/PiPPy pull request #273
Opened 2022-07-06 23:03 UTC by makslevental

MWE of `auto_parallel_strategy` API. Currently `dp_auto_parallel` doesn't do anything smart *but does insert the correct number of splits* given the `world_size`.

2022-07-07 18:50 UTC, pbelevich requested changes
We should add `local_test_forward_auto_parallel.py` to `ci_tests.yaml`, `gpu_tests.sh`, `run_all_tests.sh`

2022-07-07 18:50 UTC, pbelevich commented on test/local_test_forward_auto_parallel.py
> +    print(ec_pipe.split_gm)
No assertions about auto_parallel results?

2022-07-07 22:21 UTC, jamesr66a approved these changes
SGTM

2022-07-08 00:36 UTC, pbelevich approved these changes

2022-07-08 22:47 UTC, closed without merging