[SPMD] Implement operator admm
pytorch/PiPPy pull request #314
Opened 2022-07-29 14:09 UTC by yhcharles

2022-07-29 23:05 UTC, wanchaol approved these changes
looks good to me! Some minor comments

2022-07-29 23:05 UTC, wanchaol commented on spmd/tensor/ops/matrix_ops.py
> +    # input:replicate   mat1: replicate,  mat2: replicate
this should not goes into this function, and instead handled by the default handler inside torch_dispatch?

2022-07-29 23:05 UTC, wanchaol commented on test/spmd/tensor/test_matrix_ops.py
> +        from torch.distributed import get_rank
we can use `self.rank` to directly get the rank

2022-07-30 00:32 UTC, wanchaol requested changes
seems having some issue after testing with linear, requesting changes for output placement and need more test in nn.Linear.

2022-07-30 00:32 UTC, wanchaol commented on spmd/tensor/ops/matrix_ops.py
> +        return Tensor.from_local(local_res, device_mesh, input.placements)
Took a closer look, there're some issues here, we cannot simply assume the output placement is the same in every case, in fact, in multiple cases, they are different, we need to specify the output placement case by case.

2022-07-30 00:32 UTC, wanchaol commented on test/spmd/tensor/test_matrix_ops.py
> +        mat1 = torch.randn((world_size, world_size * 2))
also as Junjie suggested, we need to directly test on `nn.Linear` as well in additional to addmm

2022-07-30 00:32 UTC, wanchaol commented on spmd/tensor/ops/matrix_ops.py
> +        return Tensor.from_local(local_res, device_mesh, input.placements)
as a reference, please see P519128154 for a correct output placement specification

2022-08-15 20:37 UTC, yhcharles commented
Drop this PR as a new solution is merged in main branch.

2022-08-15 20:37 UTC, closed without merging